name: mixboard
channels:
  - defaults
  - conda-forge
dependencies:
  - numba=0.55.1
  - numpy=1.21.5
  - python=3.9.12
  - pip=21.2.4
  - pip:
    - billiard==3.6.4.0
    - celery==5.2.7
    - flask==2.1.2
    - gunicorn==20.1.0
    - librosa==0.9.1
    - madmom==0.16.1
    - path==16.5.0
    - pydub==0.25.1
    - python-dotenv==0.21.0
    - pyrubberband==0.3.0
    - redis==4.3.3
    - requests==2.27.1
    - rq==1.10.1
    - werkzeug==2.1.2